name: Static Link Reminder – 17 Second Rule

on:
  schedule:
    # 06:00 IST
    - cron: "30 0 * * *"

    # 11:00 IST
    - cron: "30 5 * * *"

    # 14:30 IST
    - cron: "0 9 * * *"

    # 19:00 IST
    - cron: "30 13 * * *"

    # 21:00 IST
    - cron: "30 15 * * *"

  workflow_dispatch: {}

jobs:
  send_static_link:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Send 17 sec manifestation link
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_static_17sec_manifestation.py
